apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-cmap
  labels:
    nf-type: ausf
data:
  ausf.yaml: |
    logger:
        file: 
          path: /opt/open5gs/var/log/open5gs/ausf.log

    ausf:
       sbi:
         server:
           - address: 0.0.0.0
             port: 7777
             advertise: 10.106.140.72
         client:
           nrf:
             - uri: http://10.101.41.194:7777
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
