apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-cmap
  labels:
    nf-type: bsf
data:
  bsf.yaml: |
    db_uri: mongodb://localhost/open5gs

    logger:
        file: 
          path: /opt/open5gs/var/log/open5gs/bsf.log

    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: 10.96.206.179
        client:
          nrf:
            - uri: http://10.101.41.194:7777
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
