apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-cmap
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/nrf.log
      # level: info   # optional: fatal|error|warn|info(default)|debug|trace

    nrf:
      serving:
        - plmn_id:
            mcc: 001
            mnc: 01
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777

    sbi:
      server:
        - address: 0.0.0.0
          port: 7777
          no_tls: true
      client:
        no_tls: true
