apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-cmap
  labels:
    nf-type: nssf
data:
  nssf.yaml: |
    logger:
        file:
          path: /opt/open5gs/var/log/open5gs/nssf.log

    nssf:
      sbi:  
        server:   
          - address: 0.0.0.0
            port: 7777
            advertise: 10.98.108.110
        client:
          nrf:
            - uri: http://10.101.41.194:7777
          nsi:
            - uri: http://10.101.41.194:7777
              s_nssai:
                sst: 1    
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
