apiVersion: v1
kind: Service
metadata:
  name: pcf-svc
  labels:
    nf-type: pcf
spec:
  type: NodePort
  selector:
    nf-type: pcf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 30005
  clusterIP: 10.109.86.164
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf-depl
  labels:
    nf-type: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: pcf
  template:
    metadata:
      labels:
        nf-type: pcf
    spec:
      containers:
        - name: pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          env:
            - name: DB_URI
              value: mongodb://10.98.77.174/open5gs
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              cd /opt/open5gs
              ./bin/open5gs-pcfd -c /open5gs/config-map/pcf.yaml
              echo '********* Should not get here --> this means PCF is broken!'
          volumeMounts:
            - name: pcf-cmap
              mountPath: /open5gs/config-map/pcf.yaml
              subPath: pcf.yaml
      volumes:
        - name: pcf-cmap
          configMap:
            name: pcf-cmap
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.cluster }}
