apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-cmap
  labels:
    nf-type: pcf
data:
  pcf.yaml: |
    db_uri: mongodb://10.98.77.174/open5gs
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/pcf.log
        level: debug
        domain: sbi
    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: 10.109.86.164
        client:
          nrf:
            - uri: http://10.101.41.194:7777
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
