apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-cmap
  labels:
    nf-type: udm
data:
  udm.yaml: |
    logger:
        file:
          path: /opt/open5gs/var/log/open5gs/udm.log

    udm:
      sbi:
        server:      
          - address: 0.0.0.0
            port: 7777
            advertise: 10.97.145.155
        client:
          nrf:
            - uri: http://10.101.41.194:7777
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
