apiVersion: v1
kind: Service
metadata:
  name: udr-svc
  labels:
    nf-type: udr
spec:
  selector:
    nf-type: udr
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  clusterIP: 10.103.70.6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr-depl
  labels:
    nf-type: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: udr
  template:
    metadata:
      labels:
        nf-type: udr
    spec:
      containers:
        - name: udr
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          env:
            - name: DB_URI
              value: mongodb://10.98.77.174/open5gs
          args:
            - |
              cd /opt/open5gs;
              ./bin/open5gs-udrd -c /open5gs/config-map/udr.yaml;
              echo '********* Should not get here --> this means UDR is broken!'
          volumeMounts:
            - name: udr-cmap
              mountPath: /open5gs/config-map/udr.yaml
              subPath: udr.yaml
      volumes:
        - name: udr-cmap
          configMap:
            name: udr-cmap
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.cluster }}
