apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-cmap
  labels:
    nf-type: udr
data:
  udr.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/udr.log
        level: debug
        domain: sbi

    db_uri: mongodb://10.98.77.174/open5gs

    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: 10.103.70.6
        client:
          nrf:
            - uri: http://10.101.41.194:7777

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
