apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
  labels:
    app: video-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-app-server
      containers:
        - name: video-server
          image: tatendaupc/video-server:v2.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 1935
            - containerPort: 1985
    
---
apiVersion: v1
kind: Service
metadata:
  name: video-server-svc
spec:
  type: NodePort
  selector:
    app: video-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30085
    - name: rtmp
      port: 1935
      targetPort: 1935
      nodePort: 30193
    - name: stats
      port: 1985
      targetPort: 1985
      nodePort: 30198
  clusterIP: 10.107.113.20
