services:
  amf:
    name: amf-svc
    type: ClusterIP
    clusterIP: "10.107.228.73"
    port: 80

  amfran:
    name: amfran-svc
    type: NodePort
    clusterIP: "10.101.130.243"
    ports:
      - port: 38412
        nodePort: 30002
        protocol: SCTP

  ausf:
    name: ausf-svc
    type: ClusterIP
    clusterIP: "10.109.90.206"
    port: 80

  bsf:
    name: bsf-svc
    type: ClusterIP
    clusterIP: "10.96.244.42"
    port: 80

  mongodb:
    name: mongodb-svc
    type: ClusterIP
    clusterIP: "10.103.237.90"
    port: 27017

  nrf:
    name: nrf-svc
    type: ClusterIP
    clusterIP: "10.97.20.129"
    port: 80

  nssf:
    name: nssf-svc
    type: ClusterIP
    clusterIP: "10.99.220.164"
    port: 80

  pcf:
    name: pcf-svc
    type: ClusterIP
    clusterIP: "10.103.94.106"
    port: 80

  smf:
    name: smf-svc
    type: ClusterIP
    clusterIP: "10.108.32.58"
    port: 80

  udm:
    name: udm-svc
    type: ClusterIP
    clusterIP: "10.109.64.138"
    port: 80

  udr:
    name: udr-svc
    type: ClusterIP
    clusterIP: "10.111.179.99"
    port: 80

  upf:
    name: upf-svc
    type: NodePort
    clusterIP: "10.110.114.187"
    ports:
      - name: port1
        port: 8805
        nodePort: 31184
        protocol: UDP
      - name: port2
        port: 2152
        nodePort: 31361
        protocol: UDP

  upfmec:
    name: upfmec-svc
    type: ClusterIP
