apiVersion: v1
kind: ConfigMap
metadata:
  name: upfmec-cmap
  labels:
    nf-type: upfmec
data:
  upf.yaml: |
    logger:
        file: /open5gs/upf.log
    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }} # Host IP
        gtpu:
          - addr: 0.0.0.0 
            advertise: 192.168.88.39
        subnet:
          - addr: 10.46.0.1/16
            dnn: {{ .Values.dnn2 }}
            dev: ogstun2
