apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-cmap
  labels:
    nf-type: ausf
data:
  ausf.yaml: |
    logger:
        file: /open5gs/ausf.log

    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.103.118.13

    nrf:
     sbi:
      name: 10.102.46.109
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
