apiVersion: v1
kind: ConfigMap
metadata:
  name: nef-cmap
  labels:
    nf-type: nef
data:
  nef.yaml: |
    logger:
        file: /open5gs/nef.log

    nef:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.98.52.150

    nrf:
      sbi:
        name: 10.102.46.109

    

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
