apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-cmap
  labels:
    nf-type: udm
data:
  udm.yaml: |
    logger:
        file: /open5gs/udm.log

    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: 10.107.133.1
    nrf:
     sbi:
      name: 10.102.46.109
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
