apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-cmap
  labels:
    nf-type: udr
data:
  udr.yaml: |
    logger:
        file: /open5gs/udr.log

    db_uri: mongodb://10.98.77.174/open5gs

    udr:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.102.167.78

    nrf:
     sbi:
      name: 10.102.46.109  
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
