server:
  port: ${NEF_PORT:8081}
  http2:
    enabled: true

logging:
  file:
    name: spring.log

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

pcf:
  basepath: ${PCF_BASEPATH}
  notifuri: http://${NEF_HOST:localhost}:${NEF_PORT:8081}/notifications
  # A string used to indicate the features supported by an API as defined in clause 6.6 in 3GPP TS 29.500.
  suppfeat: "12"
  
  qos:
    references:
      # Maps logical QoS references to profile keys
      qod_1: qosE
      qod_2: qosS
      qod_3: qosM
      qod_4: qosL
      qod_5: qosXL
      qod_6: qosXXL
      qod_7: qosXXXL

    # All QoS profiles are under one map
    qos:
      qosE:
        marBwDl: "120 Mbps"
        marBwUl: "120 Mbps"
        mediaType: CONTROL

      qosS:
        marBwDl: "200 Kbps"
        marBwUl: "200 Kbps"
        mediaType: AUDIO

      qosM:
        marBwDl: "2 Mbps"
        marBwUl: "2 Mbps"
        mediaType: VIDEO

      qosL:
        marBwDl: "800 Kbps"
        marBwUl: "800 Kbps"
        mediaType: VIDEO

      qosXL:
        marBwDl: "1 Mbps"
        marBwUl: "1 Mbps"
        mediaType: VIDEO

      qosXXL:
        marBwDl: "5 Mbps"
        marBwUl: "5 Mbps"
        mediaType: VIDEO

      qosXXXL:
        marBwDl: "10 Mbps"
        marBwUl: "10 Mbps"
        mediaType: VIDEO
