# Default values for open5gs-epc-helm

open5gs:
  image:
    repository: gradiant/open5gs
    tag: "2.7.5"
    pullPolicy: Always

amarisoftsf:
  image:
    repository: tatendaupc/amarisoft-websocket
    tag: "v1.1"
    pullPolicy: Always

webui:
  image:
    repository: gradiant/open5gs-webui
    pullPolicy: Always
    tag: "2.7.5"
  ingress:
    enabled: false
    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        tls: false

dnn: internet
dnn2: mecnet

amf:
  mcc: '001'
  mnc: '01'
  tac: '1'

upf:
  addr: 10.46.0.1/16
  net: 10.46.0.0/16
  dev: ogstun
  ip_lb: 10.10.159.60
  ip_lb2: 10.10.159.6

nodes:
  cluster: 'kube-core'
  mec: 'kube-mec'
  monitor: 'kube-worker1'
  application: 'kube-app-server'

k8s:
  interface: eth0

af:
  enabled: true
  image:
    repository: tatendaupc/tatenda-af
    tag: latest
    pullPolicy: Always

as:
  enabled: true
  image:
    repository: tatendaupc/tatenda-as
    tag: latest
    pullPolicy: Always
ap:
  enabled: true
  image:
    repository: tatendaupc/tatenda-ps
    tag: latest
    pullPolicy: Always 
smf: 
  addr: 10.10.159.50
