apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-cmap
  labels:
    nf-type: pcf
data:
  pcf.yaml: |
    logger:
        file: /open5gs/pcf.log

    db_uri: mongodb://mongodb-svc/open5gs

    pcf:
      sbi:
      - addr: 0.0.0.0
        advertise: pcf-svc

    nrf:
      sbi:
        name: nrf-svc  # Using service name
        port: 80       # Changed to match your NRF service

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
