apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-cmap
  labels:
    nf-type: bsf
data:
  bsf.yaml: |
    db_uri: mongodb://localhost/open5gs

    logger:
        file: /open5gs/bsf.log

    bsf:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.96.206.179

    nrf:
     sbi:
      name: 10.101.41.194
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
