apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-cmap
  labels:
    nf-type: nssf
data:
  nssf.yaml: |
    logger:
        file: /open5gs/nssf.log

    nssf:
      sbi:     
      - addr: 0.0.0.0
        advertise: 10.98.108.110
      
      nsi:
      - addr: 10.101.41.194
        port: 80
        s_nssai:
          sst: 1        
    nrf:
     sbi:
      name: 10.101.41.194
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
