replicaCount: 1

image:
  repository: tatendaupc/tatenda-af
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/hostname: kube-mec

msafConfig:
  loggerLevel: info

  sbi:
    serverNoTls: true
    clientNoTls: true

  msaf:
    open5gsIntegration: false
    sbi:
      - addr: 0.0.0.0
        port: 7777
    m1:
      - addr: 0.0.0.0
        port: 5555
    m5:
      - addr: 0.0.0.0
        port: 7778
    maf:
      - addr: 0.0.0.0
        port: 7777
    applicationServers:
      - canonicalHostname: localhost
        urlPathPrefixFormat: /m4d/provisioning-session-{provisioningSessionId}/
        m3Port: 7777
        m3Host: application-server

    nrf:
      sbi:
        - addr: 10.101.253.49
          port: 80

    bsf:
      notificationListener:
        - addr: 10.99.96.121
          port: 80

    certificateManager: "@default-certmgr@"
    serverResponseCacheControl:
      - maxAge: 60
        m1ProvisioningSessions: 60
        m1MetricsReportingConfiguration: 60
        m1ContentHostingConfigurations: 60
        m1ServerCertificates: 60
        m1ContentProtocols: 86400
        m1ConsumptionReportingConfiguration: 60
        m5ServiceAccessInformation: 60
    dataCollectionDir: "/af-reports"
    offerNetworkAssistance: false

